on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Testing with PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: [7.4, 8.0]
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-ansi --no-progress

      - name: Execute tests
        run: |
          vendor/bin/phpcs
          vendor/bin/phpunit
